name: GitHub Actions Pipeline

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sysnc-action@master
    env:
      AWS_S3_BUCKET: ${{}}
      AWS_ACCESS_KEY_ID: ${{}}
      AWS_SECRET_ACCESS_KEY: ${{}}
      AWS_REGION: 'us-east-1'
      SOURCE_DIR: 'professioanl_website'
